#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sbc
Version  : 1.3
Release  : 1
URL      : https://www.kernel.org/pub/linux/bluetooth/sbc-1.3.tar.xz
Source0  : https://www.kernel.org/pub/linux/bluetooth/sbc-1.3.tar.xz
Summary  : SBC library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: sbc-bin
Requires: sbc-lib
BuildRequires : pkgconfig(sndfile)

%description
SBC library
***********
Compilation and installation
============================

%package bin
Summary: bin components for the sbc package.
Group: Binaries

%description bin
bin components for the sbc package.


%package dev
Summary: dev components for the sbc package.
Group: Development
Requires: sbc-lib
Requires: sbc-bin
Provides: sbc-devel

%description dev
dev components for the sbc package.


%package lib
Summary: lib components for the sbc package.
Group: Libraries

%description lib
lib components for the sbc package.


%prep
%setup -q -n sbc-1.3

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492044224
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1492044224
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sbcdec
/usr/bin/sbcenc
/usr/bin/sbcinfo

%files dev
%defattr(-,root,root,-)
/usr/include/sbc/sbc.h
/usr/lib64/libsbc.so
/usr/lib64/pkgconfig/sbc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsbc.so.1
/usr/lib64/libsbc.so.1.2.1
