#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sbc
Version  : 1.5
Release  : 10
URL      : https://www.kernel.org/pub/linux/bluetooth/sbc-1.5.tar.xz
Source0  : https://www.kernel.org/pub/linux/bluetooth/sbc-1.5.tar.xz
Summary  : SBC library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: sbc-bin = %{version}-%{release}
Requires: sbc-lib = %{version}-%{release}
Requires: sbc-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32sndfile)
BuildRequires : pkgconfig(sndfile)

%description
SBC library
***********
Compilation and installation
============================

%package bin
Summary: bin components for the sbc package.
Group: Binaries
Requires: sbc-license = %{version}-%{release}

%description bin
bin components for the sbc package.


%package dev
Summary: dev components for the sbc package.
Group: Development
Requires: sbc-lib = %{version}-%{release}
Requires: sbc-bin = %{version}-%{release}
Provides: sbc-devel = %{version}-%{release}
Requires: sbc = %{version}-%{release}

%description dev
dev components for the sbc package.


%package dev32
Summary: dev32 components for the sbc package.
Group: Default
Requires: sbc-lib32 = %{version}-%{release}
Requires: sbc-bin = %{version}-%{release}
Requires: sbc-dev = %{version}-%{release}

%description dev32
dev32 components for the sbc package.


%package lib
Summary: lib components for the sbc package.
Group: Libraries
Requires: sbc-license = %{version}-%{release}

%description lib
lib components for the sbc package.


%package lib32
Summary: lib32 components for the sbc package.
Group: Default
Requires: sbc-license = %{version}-%{release}

%description lib32
lib32 components for the sbc package.


%package license
Summary: license components for the sbc package.
Group: Default

%description license
license components for the sbc package.


%prep
%setup -q -n sbc-1.5
cd %{_builddir}/sbc-1.5
pushd ..
cp -a sbc-1.5 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607645818
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1607645818
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sbc
cp %{_builddir}/sbc-1.5/COPYING %{buildroot}/usr/share/package-licenses/sbc/a7a897a4bde987e597c04f16a9c28f6d3f57916d
cp %{_builddir}/sbc-1.5/COPYING.LIB %{buildroot}/usr/share/package-licenses/sbc/32c7c5556c56cdbb2d507e27d28d081595a35a9b
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sbcdec
/usr/bin/sbcenc
/usr/bin/sbcinfo

%files dev
%defattr(-,root,root,-)
/usr/include/sbc/sbc.h
/usr/lib64/libsbc.so
/usr/lib64/pkgconfig/sbc.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libsbc.so
/usr/lib32/pkgconfig/32sbc.pc
/usr/lib32/pkgconfig/sbc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsbc.so.1
/usr/lib64/libsbc.so.1.3.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libsbc.so.1
/usr/lib32/libsbc.so.1.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sbc/32c7c5556c56cdbb2d507e27d28d081595a35a9b
/usr/share/package-licenses/sbc/a7a897a4bde987e597c04f16a9c28f6d3f57916d
